# Generated by Django 6.1 on 2026-09-10 17:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="StudySession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.CharField(
                        choices=[
                            ("pairwise_first", "Pairwise first"),
                            ("ranking_first", "Ranking first"),
                        ],
                        max_length=20,
                    ),
                ),
                ("pairwise_complete", models.BooleanField(default=False)),
                ("ranking_complete", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="RankingTrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("round_number", models.IntegerField()),
                ("movie_ids", models.JSONField()),
                ("ranking", models.JSONField()),
                ("responded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ranking_trials",
                        to="project4.studysession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PairwiseTrial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trial_number", models.IntegerField()),
                ("movie_a_id", models.IntegerField()),
                ("movie_b_id", models.IntegerField()),
                ("chosen_movie_id", models.IntegerField()),
                ("responded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pairwise_trials",
                        to="project4.studysession",
                    ),
                ),
            ],
        ),
    ]
